---
- hosts: all
  become: true

  tasks:
    - name: apt update
      apt: update_cache=yes
    
    - name: packages for Docker
      apt:
        name:
        - ca-certificates
        - curl
        - gnupg-agent
        - lsb-release

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
  
    - name: Install docker-compose
      apt: name=docker-compose

    - name: Dir for git
      ansible.builtin.file:
              path: /home/ubuntu/task17
              state: directory
              mode: '0755'

    - name: Clone git
      ansible.builtin.git:
              repo: https://github.com/d3er11/task17
              dest: /home/ubuntu/task17

    - name: Run compose
      become: True
      shell:
              cmd: "docker-compose up -d"
              chdir: /home/ubuntu/task17
